# Generated by Django 2.0.7 on 2018-07-15 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nightlystat',
            name='bedtime',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nightlystat',
            name='chores',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nightlystat',
            name='drugs',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Mild'), ('2', 'Moderate'), ('3', 'Heavy'), ('4', 'Intense')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nightlystat',
            name='exercise',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nightlystat',
            name='food',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nightlystat',
            name='guitar',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Mild'), ('2', 'Moderate'), ('3', 'Heavy'), ('4', 'Intense')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nightlystat',
            name='mood',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nightlystat',
            name='school',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nightlystat',
            name='work',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nightlystat',
            name='alcohol',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Mild'), ('2', 'Moderate'), ('3', 'Heavy'), ('4', 'Intense')], max_length=1),
        ),
    ]
